=== BeyondDimensions/AccessibleArchives/src/storage/json_schemas/Page.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Page",
  "type": "object",
  "properties": {
    "ipfs_id": {
      "type": "string",
      "description": "The IPFS CID of the page."
    },
    "transcripts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ipfs_id": {
            "type": "string",
            "description": "The IPFS CID of the transcript file."
          },
          "transcriber": {
            "type": "string",
            "description": "The person who transcribed the page."
          },
          "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "The timestamp when the page was transcribed."
          }
        },
        "required": ["ipfs_id", "transcriber", "timestamp"],
        "additionalProperties": true
      }
    },
    "content": {
      "type": "object",
      "description": "The content of the page, which can have dynamic structure."
    },
    "source": {
      "type": "object",
      "properties": {
        "original_medium": {
          "type": "string",
          "description": "The original medium of the document."
        },
        "digitisation_date": {
          "type": "string",
          "format": "date-time",
          "description": "The date when the document was digitized."
        },
        "digitiser": {
          "type": "string",
          "description": "The person or entity that digitized the document."
        }
      },
      "required": ["original_medium", "digitisation_date", "digitiser"],
      "additionalProperties": true
    }
  },
  "required": ["ipfs_id", "transcripts", "content", "source"],
  "additionalProperties": true
}

=== BeyondDimensions/AccessibleArchives/tests/test_storage/docs_template/PageMetadata/QmYZWkFRHWWDV1L98bj7aoWdi6ucz3j1SFZqgFgCtUHuJ2.json
{
  "ipfs_id": "QmYZWkFRHWWDV1L98bj7aoWdi6ucz3j1SFZqgFgCtUHuJ2",
  "transcripts": [{
    "ipfs_id": "QmbHXuQmaEKaZqRmtBvGXxDSLvGJL1KG7fq1qKFAhwR4v2",
    "transcriber": "ChatGPT",
    "timestamp": "2024-09-22T17:17:13.338515+00:00"
  }],
  "content": {},
  "source": {
    "original_medium": "PhotoCopy of BStU archive document",
    "digitiser": "anonymoys",
    "digitisation_date": "2024-09-22T17:17:13.338542+00:00"
  }
}
